/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:244cfc01-939c-41ce-9428-0c7f83747d19",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_iSA6TaR1f",
    "aws_user_pools_web_client_id": "7me969ia9t80knsgpgg73v5cjv",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://iolf5vd3qre2roztgfvtoieddy.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dfcgcc2hwfetpoojsos6lf26vq",
    "aws_user_files_s3_bucket": "redditaws8fa6b7497fe8470590b9489af9be78e9113506-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
